import Head from 'next/head'



export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Admit app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-6xl" > Hello ADMIT checking ci</h1>

      

      
    </div>
  )
}
